
jersey.datasource.url=jdbc:postgresql://postgres:5432/appdb
jersey.datasource.username=appuser
jersey.datasource.password=secret


jersey.kafka.broker=broker:29092
jersey.kafka.topic=app-events
kafka.schema.registry.url=http://schema-registry:8081