
jersey.datasource.url=jdbc:postgresql://localhost:5432/appdb
jersey.datasource.username=appuser
jersey.datasource.password=secret


jersey.kafka.broker=localhost:9092
jersey.kafka.topic=app-events
kafka.schema.registry.url=http://localhost:8081